version: '3.8'

services:
  medea:
    image: medea:latest
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../examples:/app/examples
    stdin_open: true
    tty: true